### ISSUE TITLE
Installer does not work

### ISSUE THREAD

**Issue by Mitra-M** [wagesj45/butterflow-ui#8]
- OS:  Windows 10 1803
 - butterflow-ui Version 1.1.1

I cannot install `butterflow_ui` because when I double click on` butterflow_ui.setup.msi` , it does nothing.

**Comment by wagesj45** [comment]
Where is the installer located? In my experience `*.msi` installers must be run from the same drive that your OS is installed on. (Weird, I know.)

You might also want to check that its not being caught/blocked by your anti-virus.

**Comment by Mitra-M** [comment]
Thanks for your reply .

> Where is the installer located? In my experience *.msi installers must be run from the same drive that your OS is installed on.

So weird, I do not think so, I tried c:\ and disabled the antivirus with no success, Also tried it on my other computer (Win 10 20H2)
I think you should try on a computer other than the one you use for development to see the problem.

I compiled your `butterflow-ui` project ( thanks a lot for sharing it), but unfortunately `butterflow ` gives the following error:
 
```
Traceback (most recent call last):
  File "C:/msys64/mingw64/lib/python2.7/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "C:/msys64/mingw64/lib/python2.7/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "butterflow/__main__.py", line 6, in <module>
ImportError: No module named multiprocessing
```
I saw some posts on https://github.com/dthpham/butterflow about it but could not solve it.
